name: build

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x, 22.x, 24.x]

    steps:
      - uses: actions/checkout@v5
      - name: corepack
        run: npm i -g corepack
      - uses: actions/setup-node@v5
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"
      - name: install
        run: yarn
      - name: benchmark
        run: yarn benchmark
